#
#
#

CC = g++
CXX = g++
CPPFLAGS = -I/usr/X11/include -I../image
CFLAGS = -Wall -O2
LDFLAGS = -L/usr/X11/lib -L../lib.i586-linux
LDLIBS = -lGL -lGLU -lXext -limage -lX11 -lm -lglut -lXi -lXmu

all: rgb

#rgb: rgb.cc
#	$(LD) $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) $< $(LDLIBS) -o $@
