//-----------------------------------------------
//File: Cmd_MotCtrl.h
//Author: Oliver Barth / Neobotix
//-----------------------------------------------
#ifndef CMD_MOTCTRL_INCLUDEDEF_H
#define CMD_MOTCTRL_INCLUDEDEF_H
//-----------------------------------------------
enum Cmd_MotCtrl
{
	CMD_MOTCTRL_CONNECT,
	CMD_MOTCTRL_DISCONNECT,

	CMD_MOTCTRL_SETDIGOUT,
	CMD_MOTCTRL_GETDIGIN,
	CMD_MOTCTRL_GETANALOGIN,

	CMD_MOTCTRL_SETMOTIONTYPE,

	CMD_MOTCTRL_GETPOSVEL,
	CMD_MOTCTRL_GETSTATUS,

	CMD_MOTCTRL_DISABLEBRAKE,
	CMD_MOTCTRL_ENABLEMOTOR,
	CMD_MOTCTRL_SYNCHMOTOR,
	CMD_MOTCTRL_ENABLECOMM,

	CMD_MOTCTRL_SETCMDVAL,

	CMD_MOTCTRL_SETCTRLPARA,
	CMD_MOTCTRL_GETCTRLPARA,

	CMD_MOTCTRL_SETPOSCTRL,
	CMD_MOTCTRL_GETPOSCTRL,

	CMD_MOTCTRL_SETEMSTOP,
	CMD_MOTCTRL_RESETEMSTOP,

	CMD_MOTCTRL_ERROR_STOPMOTION,
	CMD_MOTCTRL_UNKNOWN
};
//-----------------------------------------------
#endif
