//
// labcmd.h
// (C) 08/2000-11/2002 by TeSche (Torsten Scherer)
// itschere@techfak.uni-bielefeld.de
//

#ifndef _LABCMD_H
#define _LABCMD_H

#define CALL_BY_SCRIPT


typedef enum
{
#ifndef CALL_BY_SCRIPT

  CMD_PICK_TUBE_STORAGE = 0x100,
  CMD_HOLD_TUBE_SAMPLER,
  CMD_TAKE_TUBE_SAMPLER,
  CMD_HOLD_TUBE_PIPETTE,
  CMD_TAKE_TUBE_PIPETTE,
  CMD_PLACE_TUBE_WASTE,

  CMD_PLACE_TUBE_CENTRIFUGE,
  CMD_RUN_CENTRIFUGE,
  CMD_PICK_TUBE_CENTRIFUGE,
  CMD_PLACE_TUBE_FRIDGE,
  CMD_PLACE_TUBE_STORAGE,
  CMD_OPEN_CENTRIFUGE,
  CMD_CLOSE_CENTRIFUGE,
  CMD_CLOSE_CENTRIFUGE_REALLY,

  CMD_SHAKE_TUBE,

  CMD_HOLD_TUBE_SCANNER,
  CMD_TAKE_TUBE_SCANNER,

  CMD_LOADANDRUN_CENTRIFUGE,   // ++itschere20020122
  CMD_STOPANDUNLOAD_CENTRIFUGE,   // ++itschere20020122

  CMD_OPEN_HAND,
  CMD_CLOSE_HAND,

  CMD_OPEN_FRIDGE,   // ++itschere20020129
  CMD_CLOSE_FRIDGE,   // ++itschere20020129
  CMD_PLACETUBEANDCLOSE_FRIDGE,   // ++itschere20020131

  // ++itschere20021024

  CMD_PICK_CEDEX_STORAGE,
  CMD_PLACE_CEDEX_CEDEX,
  CMD_PICK_CEDEX_CEDEX,
  CMD_PLACE_CEDEX_WASTE,

  // ++itschere20021114

  CMD_PICK_TUBE_STORAGEBARCODE,
  CMD_PLACE_TUBE_STORAGEBARCODE,

  // ++itschere20021121

  CMD_HOLD_CEDEX_PIPETTE,
  CMD_TAKE_CEDEX_PIPETTE,

  // ++itschere20021122

  CMD_ROTATE_TUBE_SCANNER,

  // ++itschere20030317

  CMD_PARK_CHARGER,
  CMD_UNPARK_CHARGER,

  // ++itschere20030502

  CMD_HOLD_TUBE_SAMPLER2,
  CMD_TAKE_TUBE_SAMPLER2

#else

  // ++itschere20031017: completely different way of handling things

  CMD_EXEC_SCRIPT = 0x400

#endif

} EROBOTCMD;


typedef enum
{
  CMD_GET_IMAGE = 0x200
} ECAMERACMD;


typedef enum
{
  CMD_GET_MAP_IMAGE = 0x300
} EMAPCMD;


#endif // _ROBOTCMD_H
