######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 6 16:05:12 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ../
INCLUDEPATH += . ../
QT += network

# Input
HEADERS += udpclient.h logger.h packet.h
SOURCES += udpclient.cpp logger.cpp packet.cpp
