/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uhh_fbi_tams_iowarrior_IOwarriorUSB */

#ifndef _Included_uhh_fbi_tams_iowarrior_IOwarriorUSB
#define _Included_uhh_fbi_tams_iowarrior_IOwarriorUSB
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: iowarrior */
/*
 * Class:     uhh_fbi_tams_iowarrior_IOwarriorUSB
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uhh_fbi_tams_iowarrior_IOwarriorUSB_close
  (JNIEnv *, jclass);

/*
 * Class:     uhh_fbi_tams_iowarrior_IOwarriorUSB
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uhh_fbi_tams_iowarrior_IOwarriorUSB_init
  (JNIEnv *, jclass);

/*
 * Class:     uhh_fbi_tams_iowarrior_IOwarriorUSB
 * Method:    set
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_uhh_fbi_tams_iowarrior_IOwarriorUSB_set
  (JNIEnv *, jclass, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
