######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 8 15:08:33 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
QT += network
INCLUDEPATH += . ../../../src/mobiled/ ../../../src/ /opt/sun-jdk-1.6.0.03/include/ /opt/sun-jdk-1.6.0.03/include/linux/
LIBS += -ljvm
LIBPATH += /opt/sun-jdk-1.6.0.03/lib/ /opt/sun-jdk-1.6.0.03/jre/lib/amd64/server/ /usr/lib/jvm/java-1.6.0-sun-1.6.0/lib /usr/lib/jvm/java-1.6.0-sun-1.6.0/jre/lib/i386/server/

# Input
SOURCES +=	test.cpp \
		../../../src/mobiled/java.cpp \
		../../../src/pose.cpp \
		../../../src/configuration.cpp \
		../../../src/conversion.cpp \
		../../../src/lasermark.cpp \
		../../../src/logger.cpp

HEADERS +=	../../../src/mobiled/java.h \
		../../../src/pose.h \
		../../../src/configuration.h \
		../../../src/conversion.h \
		../../../src/lasermark.h \
		../../../src/logger.h
